source 'http://rubygems.org'

gem 'rails', '3.0.9'

gem 'mysql2', '~> 0.2.6'

gem 'fb_graph'

gem 'delayed_job'

gem 'zodiac', '>= 0.2'

group :development do
  gem 'ruby-debug'
  gem 'capistrano'
end
